/**
 * Type definitions for the Outseta embed script (window.Outseta).
 * These describe the client-side SDK loaded via script tag,
 * NOT the REST API types generated by Orval.
 */

export interface OutsetaUser {
  Uid: string;
  Email: string;
  FirstName?: string;
  LastName?: string;
  FullName?: string;
  Account?: {
    Uid?: string;
    Name?: string;
    CurrentSubscription?: {
      Uid?: string;
      Plan?: {
        Uid?: string;
        Name?: string;
      };
      SubscriptionAddOns?: Array<{
        AddOn?: {
          Uid?: string;
          Name?: string;
        };
      }>;
    };
  };
  [key: string]: unknown;
}

export type OutsetaWidgetMode = "popup" | "embed";
export type AuthWidgetMode = "login" | "register" | "login|register";

export interface AuthWidgetOptions {
  widgetMode?: AuthWidgetMode;
  authenticationCallbackUrl?: string;
  mode?: OutsetaWidgetMode;
  registrationDefaults?: string | Record<string, unknown>;
  [key: string]: unknown;
}

export interface ProfileWidgetOptions {
  tab?:
    | "profile"
    | "billing"
    | "planChange"
    | "purchaseAddOn"
    | "passwordChange"
    | "teamMembers";
  mode?: OutsetaWidgetMode;
  stateProps?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface SupportWidgetOptions {
  mode?: OutsetaWidgetMode;
  [key: string]: unknown;
}

export interface EmailListWidgetOptions {
  emailListUid: string;
  mode?: OutsetaWidgetMode;
  [key: string]: unknown;
}

export interface LeadCaptureWidgetOptions {
  formUid: string;
  mode?: OutsetaWidgetMode;
  [key: string]: unknown;
}

export interface OutsetaEmbed {
  setAccessToken: (token: string) => void;
  getAccessToken: () => Promise<string | null>;
  getUser: () => Promise<OutsetaUser>;
  logout: () => void;
  on: (event: string, callback: () => void) => void;
  auth: {
    open: (options?: AuthWidgetOptions) => void;
  };
  profile: {
    open: (options?: ProfileWidgetOptions) => void;
  };
  support?: {
    open: (options?: SupportWidgetOptions) => void;
  };
  emailList?: {
    open: (options: EmailListWidgetOptions) => void;
  };
  leadCapture?: {
    open: (options: LeadCaptureWidgetOptions) => void;
  };
}

declare global {
  interface Window {
    Outseta?: OutsetaEmbed;
  }
}
